#ifndef PARAM_H
#define PARAM_H

#include <SDL2/SDL.h>
#include <SDL2/SDL_image.h>
	
#include <SDL2/SDL_ttf.h>
// SCREEN PARAMETERS:
#define FRAME_RATE 60
#define DEFAULT_SCREEN_WIDTH 1920
#define DEFAULT_SCREEN_HEIGHT 1080

// GAME PARAMETERS:

#define DEFAULT_SIZE_OF_CELL 100
#define DEFAULT_MAP_WIDTH 11
#define DEFAULT_MAP_HEIGHT 11

// PLAYER PARAMETERS:
#define PLAYER_SPEED_FRAME_RATE 2
#define PLAYER_FRAME_RATE (FRAME_RATE/PLAYER_SPEED_FRAME_RATE)
#define DEFAULT_IMMUNED (BOMB_FRAME/2)
#define DEFAULT_DEATH 60

// SPRITE:
#define DEFAULT_SIZE_OF_HEART (DEFAULT_SIZE_OF_CELL / 2)
#endif